const HTTP_OK_STATUS = 200;
const HTTP_NO_CONTENT = 204;
const HTTP_NOT_FOUND = 404;
const HTTP_CREATED_STATUS = 201;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_NO_CONTENT,
  HTTP_NOT_FOUND,
  HTTP_CREATED_STATUS,
};
